Adds custom reporter capability
ember-a11y/ember-a11y-testing pull request #210
Opened 2020-09-03 19:34 UTC by scalvert

As part of #207, this PR adds a new reporter system that will allow us to provide custom reporting for accessibility violations for test runs.

The reporter conforms to the following interface:

```ts
interface A11yAuditReporter {
  (axeResults: AxeResults): Promise<void>;
}
```

A `setCustomReporter` is provided, allowing you to provide a custom `A11yAuditReporter` implementation.

```ts
export function setCustomReporter(
  customReporter: A11yAuditReporter = DEFAULT_REPORTER
): void;
```

This API provides the flexibility to shape the violations in any format you want.

2020-09-03 21:27 UTC, rwjblue requested changes

2020-09-03 21:27 UTC, rwjblue commented on addon-test-support/reporter.ts
> +To rerun this specific failure, use the following query params: &${QUnit.config.current.testId}&enableA11yAudit=true`
```suggestion
To rerun this specific failure, use the following query params: &testId=${QUnit.config.current.testId}&enableA11yAudit=true`
```

2020-09-03 21:27 UTC, rwjblue commented on tests/acceptance/reporter-test.ts
> +  });
```suggestion
  setupApplicationTest(hooks);

  hooks.afterEach(function() {
    setCustomReporter(); // reset to default value
  });
  
  test('setCustomReporter can correctly set a custom reporter in favor of default', async function (assert) {
    assert.expect(1);

    setCustomReporter(async (axeResult: AxeResults) => {
      assert.equal(axeResult.violations.length, 3);
    });

    await visit('/');

    await a11yAudit();
  });
```

2020-09-03 22:39 UTC, drewlee commented on addon-test-support/reporter.ts
> +To rerun this specific failure, use the following query params: &${QUnit.config.current.testId}&enableA11yAudit=true`
That's cool!

2020-09-03 23:04 UTC, scalvert commented on addon-test-support/reporter.ts
> +To rerun this specific failure, use the following query params: &${QUnit.config.current.testId}&enableA11yAudit=true`
Oh good find!

2020-09-03 23:05 UTC, scalvert commented on tests/acceptance/reporter-test.ts
> +  });
We have one test...but FINE. 😄

2020-09-04 00:38 UTC, scalvert commented
@rwjblue I'm gonna stop accepting your suggestions since they keep killing my formatting!! JK! Fixed the prettier errors.

2020-09-04 13:54 UTC, rwjblue commented
Haha! FINE! 😝

2020-09-04 13:55 UTC, rwjblue approved these changes

2020-09-04 13:55 UTC, merged